spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
#      ddl-auto: create
#      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost/TaskManager
    username: postgres
    password: 12345
    driverClassName: org.postgresql.Driver